version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./vite-project/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./vite-project:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./dj_backend/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
